### ISSUE TITLE
Does not seem to work on Linux (tested on Ubuntu 20.04.3 LTS)

### ISSUE THREAD

**Issue by kevwkev** [philphilphil/RSS2Pushover#1]
Does not seem to work on Linux.
Tested on Ubuntu 20.04.3 LTS

**Comment by philphilphil** [comment]
I updated the project and its dependencies to .NET6, please try again.
If its still not working please provide an error message.
Thanks!

**Comment by kevwkev** [comment]
Thanks for the quick update! The program works perfectly fine on Windows. Unfortunately, still no luck on Linux., there are no error messages, just the following messages:
"Starting up... "
"11/13/2021 3:39 PM Checking Feed.." 

- No data has been written to archive.txt when running the program on Linux.
- Already chmod 777 on  ./appsettings.json  ./archive.txt ./RSS2Pushover
- Even tried renaming appsettings.json to appsettings1.json. On Windows, it will quit with a "configuration file not found" error, but no error on Linux.
- Also tested on MacOS Big Sur, same as Linux, the program runs, but no error and push notification.

the command used to compile:
dotnet publish -c release -r ubuntu.20.04-x64 --self-contained (also tried without --self-contained and installed .Net core runtime in Linux)

**Comment by philphilphil** [comment]
Thanks, i will investigate!

**Comment by philphilphil** [comment]
I'm very sorry, that was some very, very bad exception handling in my code. It was caught but never thrown.
Error is fixed and it now works also on Mac OS and hopefully Linux.
Due testing i found out that there are some RSS-Feeds which do not give out the "guid" for the items, if thats the case with the feed you are trying to load it might fail again because the programm needs the guid to save what he already pushed. there would be others ways to save it but thats currently not implemented.

**Comment by kevwkev** [comment]
Thanks for the update! I tested on Linux and it's still not working, no error message. But continue to work fine in Windows.

**Comment by philphilphil** [comment]
Sorry again! Now it works. The building of the path was wrong, not sure why it worked on Mac but not on Linux. I tested it on Ubuntu :)

**Comment by kevwkev** [comment]
Working perfectly on Linux. Thanks again for the update!
